name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Cache uv and pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            .venv
            uv.lock
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Run Makefile (all targets)
        run: |
          source .venv/bin/activate
          make all
      - name: Run coverage (fail if <65%)
        run: |
          source .venv/bin/activate
          make coverage
