name: Test

on:
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Cache uv and pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            .venv
            uv.lock
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}

      - name: Create and sync venv
        run: |
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Run pytest
        run: |
          source .venv/bin/activate
          PYTHONPATH=. python -m pytest --maxfail=2 --disable-warnings -q
